language: python
os:
  - linux
  - osx
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
  - "3.5"
  - "3.6"
  
install:
  - pip install --upgrade setuptools
  - pip install -r requirements_travis.txt

script: 
  - pytest difi --cov=difi

after_success:
  - coveralls
